---
- name: "STEP 2: Display Transferred Data"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Print the variable passed via set_stats"
      debug:
        msg: "Data received from previous job: {{ shared_namespace }}"
      failed_when: shared_namespace is not defined
